#!/usr/bin/env bash

JQ_EXE=$(command -v jq)
if [[ ! -x "$JQ_EXE" ]]; then
   echo "$(tput setaf 1)jq is not available. Please upgrade docker-devbox.$(tput sgr0)"
   echo "$(tput setaf 3)More information at https://github.com/inetum-orleans/docker-devbox$(tput sgr0)"
   return
fi

YQ_EXE=$(command -v yq)
if [[ ! -x "$YQ_EXE" ]]; then
   echo "$(tput setaf 1)yq is not available. Please upgrade docker-devbox.$(tput sgr0)"
   echo "$(tput setaf 3)More information at https://github.com/inetum-orleans/docker-devbox$(tput sgr0)"
   return
fi
