#!/usr/bin/env bash

if [ -d "$DOCKER_DEVBOX_SCRIPTS_PATH/.bin" ] ; then
  chmod +x "$DOCKER_DEVBOX_SCRIPTS_PATH/.bin"/*
  autostash PATH="$DOCKER_DEVBOX_SCRIPTS_PATH/.bin:$PATH"
fi

if [ -d "$DOCKER_DEVBOX_DIR/.bin" ] ; then
  chmod +x "$DOCKER_DEVBOX_DIR/.bin"/*
  autostash PATH="$DOCKER_DEVBOX_DIR/.bin:$PATH"
fi
