#!/usr/bin/env bash

if [[ -z "$DOCKER_DEVBOX_DISABLE_COPY_CA_CERTIFICATES" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
  CA_CERTIFICATES_MANUAL_DIR="$CA_CERTIFICATES_DIR.manual"

  if [[ -f "/${CA_CERTIFICATES_DIR:?}/.gitignore" ]]; then
    find "/${CA_CERTIFICATES_DIR:?}" -type f -not -name '.gitignore' -delete
  else
    rm -Rf "/${CA_CERTIFICATES_DIR:?}"
  fi

  if [[ -d "$CA_CERTIFICATES_MANUAL_DIR" ]]; then
    for CERT in "$CA_CERTIFICATES_MANUAL_DIR"/*; do
      mkdir -p "/${CA_CERTIFICATES_DIR:?}"
      cp -L "$CERT" "$CA_CERTIFICATES_DIR"
    done
  fi

  if [[ -n "$DOCKER_DEVBOX_CA_CERTIFICATES" ]]; then
    for CERT in $DOCKER_DEVBOX_CA_CERTIFICATES; do
      mkdir -p "/${CA_CERTIFICATES_DIR:?}"
      if [[ -f "$CA_CERTIFICATES_DIR/$(basename "$CERT")" ]]; then
        if _cp_file_if_different "$CERT" "$CA_CERTIFICATES_DIR/$(basename "$CERT")"; then
          echo "$(tput setaf 1)CA Certificate provided by DOCKER_DEVBOX_CA_CERTIFICATES doesn't match the one from directory \"$(_utils_relative_path "$CA_CERTIFICATES_MANUAL_DIR")\" ($(basename "$CERT"))$(tput sgr0)"
          echo "$(tput setaf 3)You should copy the certificate $(basename $CERT) from \"$(_utils_relative_path "$CA_CERTIFICATES_DIR")\" to \"$(_utils_relative_path "$CA_CERTIFICATES_MANUAL_DIR")\"$(tput sgr0)"
          echo "$(tput setaf 3)If both certificates needs to be kept, you should rename \"$(_utils_relative_path "$CA_CERTIFICATES_MANUAL_DIR")/$(basename "$CERT")\" to avoid this conflict$(tput sgr0)"
        fi
      else
        cp -f "$CERT" "$CA_CERTIFICATES_DIR/$(basename "$CERT")"
      fi
    done
  fi

  if [[ -d $CA_CERTIFICATES_DIR ]]; then
    if [[ -n "$(ls -A "$CA_CERTIFICATES_DIR")" ]]; then
      for cert in "$CA_CERTIFICATES_DIR"/*; do
        echo "$(tput setaf 2)CA Certificate is available in build context ($(basename "$cert"))$(tput sgr0)"
      done
    fi
  fi
fi



