#!/usr/bin/env bash
if [[ -z $DOCKER_DEVBOX_REVERSE_PROXY_TYPE ]]; then
  autostash DOCKER_DEVBOX_REVERSE_PROXY_TYPE
  REVERSE_PROXY_RESPONSE=$(set -o pipefail && curl --max-time 1 -s "http://127.0.0.1/api/version")

  if [ $? -ne 0 ]; then
    echo "$(tput setaf 1)Reverse proxy is unavailable (connection failed)!$(tput sgr0)"
  else
    if echo "$REVERSE_PROXY_RESPONSE" | grep -q nginx; then
      DOCKER_DEVBOX_REVERSE_PROXY_TYPE="nginx-proxy"
    else
      TRAEFIK_VERSION=$(echo "$REVERSE_PROXY_RESPONSE" | jq .Version -r)

      if [[ "${TRAEFIK_VERSION:0:2}" == "v1" ]]; then
        DOCKER_DEVBOX_REVERSE_PROXY_TYPE="traefik (v1)"
      elif [[ "${TRAEFIK_VERSION:0:1}" == "2" ]]; then
        DOCKER_DEVBOX_REVERSE_PROXY_TYPE="traefik (v2)"
      fi
    fi
  fi

  if [[ ! -z $DOCKER_DEVBOX_REVERSE_PROXY_TYPE ]]; then
    echo "$(tput setaf 2)$DOCKER_DEVBOX_REVERSE_PROXY_TYPE is running$(tput sgr0)"
  else
    echo "$(tput setaf 1)Reverse proxy is unavailable (unkown response)!$(tput sgr0)"
  fi
else
  echo "$(tput setaf 2)$DOCKER_DEVBOX_REVERSE_PROXY_TYPE is assumed$(tput sgr0)"
fi
