#!/usr/bin/env bash
. "$DOCKER_DEVBOX_SCRIPTS_PATH/.bash.lib.d/50-docker"

for DOCKERFILE in "${DOCKER_DEVBOX_DIR}/.docker/"**/Dockerfile; do
  if grep -Eq ".*fixuid.*?\.tar\.gz" "$DOCKERFILE"; then
    entrypoint=$(cat "$DOCKERFILE" | sed -rn 's!(ENTRYPOINT )(.*)!\2!p')
    image_entrypoint=$(echo $entrypoint | jq -Mc '. as $entrypoint | select($entrypoint[0] != "fixuid") | $entrypoint')

    if [[ -z "$image_entrypoint" ]]; then
      image=$(cat "$DOCKERFILE" | sed -rn 's!(FROM )(.*)!\2!p')
      image_entrypoint=$(_docker_find_image_entrypoint "$image")
    fi

    fixuid_entrypoint=$(echo "$image_entrypoint" | jq -Mc '. |= ["fixuid", "-q"] + .')

    image_cmd=$(cat "$DOCKERFILE" | sed -rn 's!(CMD )(.*)!\2!p')
    if [[ -z "$image_cmd" ]]; then
      image=$(cat "$DOCKERFILE" | sed -rn 's!(FROM )(.*)!\2!p')
      image_cmd=$(_docker_find_image_cmd "$image")
    fi

    image_cmd=$(echo "$image_cmd" | jq -Mc '.')

    if [[ ! $(cat "$DOCKERFILE" | sed -rn 's!(ENTRYPOINT )(.*)!\1'"$fixuid_entrypoint"'!') > "$DOCKERFILE.sed" && ! -z "$fixuid_entrypoint" ]]; then
      rm -f "$DOCKERFILE.sed"
      echo "ENTRYPOINT $fixuid_entrypoint" >> "$DOCKERFILE"
    else
      mv -f "$DOCKERFILE.sed" "$DOCKERFILE"
    fi
    if [[ ! $(cat "$DOCKERFILE" | sed -rn 's!(CMD )(.*)!\1'"$image_cmd"'!' > "$DOCKERFILE.sed") && ! -z "$image_cmd" ]]; then
      rm -f "$DOCKERFILE.sed"
      echo "CMD $image_cmd" >> "$DOCKERFILE"
    else
      mv -f "$DOCKERFILE.sed" "$DOCKERFILE"
    fi
  fi
done
