#!/usr/bin/env bash
if [[ "$SHOULD_COPY_MKCERT_CA_CERTIFICATE" == "1" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
  MKCERT_EXE=$(command -v mkcert)

  if [[ -x "$MKCERT_EXE" ]]; then
    if [[ ! -f "$(mkcert -CAROOT)/rootCA.pem" ]]; then
      mkcert -install
    fi

    mkdir -p "/${CA_CERTIFICATES_DIR:?}"
    cp "$(mkcert -CAROOT)/rootCA.pem" "$CA_CERTIFICATES_DIR"/mkcert-ca.pem
    echo "$(tput setaf 2)Mkcert CA Certificate is available in docker build context (mkcert-ca.pem)$(tput sgr0)"
  fi
fi
