#!/usr/bin/env bash
CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"

for cert in "${CA_CERTIFICATES_DIR}"/*.pem; do
  if [[ -f "$cert" ]]; then
    mv "$cert" "${CA_CERTIFICATES_DIR}/$(basename "$cert" .pem).crt"
  fi
done

if [[ -d "$CA_CERTIFICATES_DIR" ]]; then
  for image_directory in $(ls -d "$DOCKER_DEVBOX_DIR/.docker/"*/ 2>/dev/null); do
    cp -fR "$CA_CERTIFICATES_DIR" "$image_directory"
  done
fi
