#!/usr/bin/env bash

if [[ "$DOCKER_DEVBOX_COPY_SELF_CA_CERTIFICATE" == "1" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"

  cacert=$(cfssl-cli info)

  if [[ ! -z cacert ]]; then
    mkdir -p "${CA_CERTIFICATES_DIR}"
    echo "$cacert" > "${CA_CERTIFICATES_DIR}/cfssl-ca.pem"
    echo "$(tput setaf 2)CFSSL CA Certificate is available in build context (cfssl-ca.pem)$(tput sgr0)"
  else
    echo "$(tput setaf 1)Can't get CA certificate for CFSSL certificates.$(tput sgr0)"
  fi
fi
