#!/usr/bin/env bash
if [[ "$SHOULD_COPY_MKCERT_CA_CERTIFICATE" == "1" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
  MKCERT_EXE=$(command -v mkcert)

  if [[ $EUID -eq 0 ]]; then
    SUDO_EXE=""
  else
    SUDO_EXE=$(command -v sudo)
    if [[ ! -x "$SUDO_EXE" ]]; then
      echo "sudo is not available." 2>&1 | tee -a "$_LOG"
      SUDO_EXE=""
    else
      SUDO_EXE="$SUDO_EXE -E"
    fi
  fi

  if [[ -x "$MKCERT_EXE" ]]; then
    if [[ ! -f "$(mkcert -CAROOT)/rootCA.pem" ]]; then
      $SUDO_EXE $MKCERT_EXE -install
    fi

    mkdir -p "/${CA_CERTIFICATES_DIR:?}"
    cp "$(mkcert -CAROOT)/rootCA.pem" "$CA_CERTIFICATES_DIR"/mkcert-ca.pem
    echo "$(tput setaf 2)Mkcert CA Certificate is available in docker build context (mkcert-ca.pem)$(tput sgr0)"
  fi
fi
