#!/usr/bin/env bash

if [[ -z "$DOCKER_DEVBOX_DISABLE_COPY_CA_CERTIFICATES" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
  rm -Rf "/${CA_CERTIFICATES_DIR:?}"

  if [[ -n "$DOCKER_DEVBOX_CA_CERTIFICATES" ]]; then
    for CERT in $DOCKER_DEVBOX_CA_CERTIFICATES; do
      mkdir -p "/${CA_CERTIFICATES_DIR:?}"
      cp -L "$CERT" "$CA_CERTIFICATES_DIR"
    done

    for pem in "$CA_CERTIFICATES_DIR"/*.pem; do
      mkdir -p "/${CA_CERTIFICATES_DIR:?}"
      mv "$pem" "$CA_CERTIFICATES_DIR/$(basename "$pem" .pem).crt"
    done

    if [[ -n "$(ls -A "$CA_CERTIFICATES_DIR")" ]]; then
      for cert in "$CA_CERTIFICATES_DIR"/*; do
        echo "$(tput setaf 2)CA Certificate has been copied to docker build context ($(basename "$cert"))$(tput sgr0)"
      done
    fi
  fi
fi



