#!/usr/bin/env bash

CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
FILE_COUNT=0
rm -Rf "/${CA_CERTIFICATES_DIR:?}"

if [ -n "$DOCKER_DEVBOX_CA_CERTIFICATES" ]; then
  for CERT in $DOCKER_DEVBOX_CA_CERTIFICATES; do
    mkdir -p "/${CA_CERTIFICATES_DIR:?}"
    rm -f "$CA_CERTIFICATES_DIR/.empty"
    cp -L "$CERT" "$CA_CERTIFICATES_DIR"
  done

  for pem in "$CA_CERTIFICATES_DIR"/*.pem; do
    mkdir -p "/${CA_CERTIFICATES_DIR:?}"
    rm -f "$CA_CERTIFICATES_DIR/.empty"
    mv "$pem" "$CA_CERTIFICATES_DIR/$(basename "$pem" .pem).crt"
  done

  if [ -n "$(ls -A "$CA_CERTIFICATES_DIR")" ]; then
    for cert in "$CA_CERTIFICATES_DIR"/*; do
      echo "$(tput setaf 2)$(basename "$cert")$(tput sgr0)"
      FILE_COUNT=$((FILE_COUNT+1))
    done
  fi
fi

MKCERT=$(command -v mkcert)

if [ -x "$MKCERT" ]; then
  if [ ! -f "$(mkcert -CAROOT)/rootCA.pem" ]; then
    mkcert -install
  fi

  mkdir -p "/${CA_CERTIFICATES_DIR:?}"
  rm -f "$CA_CERTIFICATES_DIR/.empty"
  cp "$(mkcert -CAROOT)/rootCA.pem" "$CA_CERTIFICATES_DIR"/mkcert-ca.pem
  echo "$(tput setaf 2)mkcert-ca.pem$(tput sgr0)"
  FILE_COUNT=$((FILE_COUNT+1))
fi

if [ -f "$DOCKER_DEVBOX_CERTS_PATH/cfssl-ca/rootCA.pem" ]; then
  mkdir -p "/${CA_CERTIFICATES_DIR:?}"
  rm -f "$CA_CERTIFICATES_DIR/.empty"
  cp "$DOCKER_DEVBOX_CERTS_PATH/cfssl-ca/rootCA.pem" "$CA_CERTIFICATES_DIR"/cfssl-ca.pem
  echo "$(tput setaf 2)cfssl-ca.pem$(tput sgr0)"
  FILE_COUNT=$((FILE_COUNT+1))
fi

if [ "$FILE_COUNT" -eq "0" ]; then
  echo "$(tput setaf 3)No certificates found.$(tput sgr0)"
  echo "$(tput setaf 3)Creating .gitempty file$(tput sgr0)"
  touch "$CA_CERTIFICATES_DIR/.gitempty"
fi

