#!/usr/bin/env bash

if [[ -z "$DOCKER_DEVBOX_DISABLE_COPY_CA_CERTIFICATES" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
  CA_CERTIFICATES_MANUAL_DIR="$CA_CERTIFICATES_DIR.manual"

  rm -Rf "/${CA_CERTIFICATES_DIR:?}"

  if [[ -n "$DOCKER_DEVBOX_CA_CERTIFICATES" ]]; then
    for CERT in $DOCKER_DEVBOX_CA_CERTIFICATES; do
      mkdir -p "/${CA_CERTIFICATES_DIR:?}"
      cp -L "$CERT" "$CA_CERTIFICATES_DIR"
    done
  fi

  if [[ -d "$CA_CERTIFICATES_MANUAL_DIR" ]]; then
    for CERT in "$CA_CERTIFICATES_MANUAL_DIR"/*; do
      mkdir -p "/${CA_CERTIFICATES_DIR:?}"
      cp -L "$CERT" "$CA_CERTIFICATES_DIR"
    done
  fi

  if [[ -d $CA_CERTIFICATES_DIR ]]; then
    if [[ -n "$(ls -A "$CA_CERTIFICATES_DIR")" ]]; then
      for cert in "$CA_CERTIFICATES_DIR"/*; do
        echo "$(tput setaf 2)CA Certificate is available in build context ($(basename "$cert"))$(tput sgr0)"
      done
    fi
  fi
fi



