#!/usr/bin/env bash
. "$DOCKER_DEVBOX_SCRIPTS_PATH/.bash.lib.d/50-docker"

for DOCKERFILE in "${DOCKER_DEVBOX_DIR}/.docker/"**/Dockerfile; do
  [[ -e "$DOCKERFILE" ]] || continue
  if grep -Eq ".*fixuid.*?\.tar\.gz" "$DOCKERFILE"; then
    echo "$(tput setaf 2)Generating fixuid ENTRYPOINT/CMD for $(_utils_relative_path ${DOCKERFILE}) ...$(tput sgr0)"

    entrypoint=$(cat "$DOCKERFILE" | sed -E -n 's!^(ENTRYPOINT\s+)(.+?)$!\2!p')
    image_entrypoint=$(echo "$entrypoint" | jq -Mc '. as $entrypoint | select($entrypoint[0] != "fixuid") | $entrypoint')

    if [[ -z "$image_entrypoint" ]]; then
      image=$(cat "$DOCKERFILE" | sed -E -n 's!^(FROM\s+)(.+?)$!\2!p')
      _docker_find_image_entrypoint "$image" image_entrypoint
    fi

    fixuid_entrypoint=$(echo "$image_entrypoint" | jq -Mc '. |= ["fixuid", "-q"] + .')

    image_cmd=$(cat "$DOCKERFILE" | sed -E -n 's!^(CMD\s+)(.+?)$!\2!p')
    base_image_cmd="$image_cmd"
    if [[ -z "$image_cmd" ]]; then
      image=$(cat "$DOCKERFILE" | sed -E -n 's!^(FROM\s+)(.+?)$!\2!p')
      _docker_find_image_cmd "$image" base_image_cmd
      base_image_cmd=$(echo "$base_image_cmd" | jq -Mc '.')
    else
      image_cmd=$(echo "$image_cmd" | jq -Mc '.')
    fi

    cat "$DOCKERFILE" | sed -E -s 's!^(ENTRYPOINT\s+).+?!\1'${fixuid_entrypoint}'!g' > "$DOCKERFILE.sed"
    if cmp --silent "$DOCKERFILE" "$DOCKERFILE.sed"; then
      rm -f "$DOCKERFILE.sed"
      echo "ENTRYPOINT $fixuid_entrypoint" >> "$DOCKERFILE"
      #echo "$(tput setaf 3)ENTRYPOINT $fixuid_entrypoint ($(_utils_relative_path ${DOCKERFILE}))$(tput sgr0)"
    else
      mv -f "$DOCKERFILE.sed" "$DOCKERFILE"
    fi

    cat "$DOCKERFILE" | sed -E -s 's!^(CMD\s+).+?$!\1'${image_cmd}'!g' > "$DOCKERFILE.sed"
    if cmp --silent "$DOCKERFILE" "$DOCKERFILE.sed"; then
      rm -f "$DOCKERFILE.sed"
      if [[ -z ${image_cmd} ]]; then
        echo "CMD $base_image_cmd" >> "$DOCKERFILE"
      fi
      #echo "$(tput setaf 3)CMD $image_cmd ($(_utils_relative_path ${DOCKERFILE}))$(tput sgr0)"
    else
      mv -f "$DOCKERFILE.sed" "$DOCKERFILE"
    fi
  fi
done
