#!/usr/bin/env bash

if [[ "${DOCKER_DEVBOX_SSL}" == "mkcert" && -z "$DOCKER_DEVBOX_DISABLE_COPY_CA_CERTIFICATES" && ! -z "$DOCKER_DEVBOX_COPY_SELF_CA_CERTIFICATE" ]]; then
  CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
  MKCERT=$(command -v mkcert)

  if [ -x "$MKCERT" ]; then
    if [ ! -f "$(mkcert -CAROOT)/rootCA.pem" ]; then
      mkcert -install
    fi

    mkdir -p "/${CA_CERTIFICATES_DIR:?}"
    rm -f "$CA_CERTIFICATES_DIR/.empty"
    cp "$(mkcert -CAROOT)/rootCA.pem" "$CA_CERTIFICATES_DIR"/mkcert-ca.pem
    echo "$(tput setaf 2)mkcert-ca.pem$(tput sgr0)"
  fi
fi
