#!/usr/bin/env bash

_utils_relative_path() {
  local ABSOLUTE_PATH="$1"
  local __ret=$2
  local ret=$(echo "$ABSOLUTE_PATH" | sed -E "s;""$DOCKER_DEVBOX_DIR""[/\\]?;;g")

  if [[ "$__ret" ]]; then
    eval $__ret="'$ret'"
  else
    echo "$ret"
  fi
}

_file_is_different() {
SRC="$1"
DEST="$2"

if [[ -f "$SRC" ]] && [[ ! -f "$DEST" ]]; then
  return 0
else
  if [[ ! -f "$SRC" ]] && [[ -f "$DEST" ]]; then
    return 0
  else
    if [[ -f "$SRC" ]] && [[ -f "$DEST" ]] && ! cmp -s "$SRC" "$DEST"; then
      return 0
    fi
  fi
fi

return 1
}
_cp_file_if_different() {
SRC="$1"
DEST="$2"

if [[ -f "$SRC" ]] && [[ ! -f "$DEST" ]]; then
  cp -f "$SRC" "$DEST"
  return 0
else
  if [[ ! -f "$SRC" ]] && [[ -f "$DEST" ]]; then
    rm "$DEST"
    return 0
  else
    if [[ -f "$SRC" ]] && [[ -f "$DEST" ]] && ! cmp -s "$SRC" "$DEST"; then
      cp -f "$SRC" "$DEST"
      return 0
    fi
  fi
fi

return 1
}
