#!/usr/bin/env bash

if [ "$1" = "--default-entrypoint" ]; then
  shift
  IMAGE=$(_docker_find_service_image "$1")
  $(_docker_find_image_entrypoint "$IMAGE" ENTRYPOINT)
  dc run --rm --entrypoint "$ENTRYPOINT" "$@"
else
  dc run --rm "$@"
fi
