#!/usr/bin/env bash
. "$DOCKER_DEVBOX_SCRIPTS_PATH/.bash.lib.d/50-docker"

_RUN_REVERSE_PROXY_ENABLE_ARGS=
if [[ -z "${_RUN_REVERSE_PROXY_ENABLE}" ]]; then
  _RUN_REVERSE_PROXY_ENABLE_ARGS="--label traefik.enable=false"
fi

if [[ ! -z "${_RUN_DEFAULT_ENTRYPOINT}" ]]; then
  _docker_find_service_image "$1" IMAGE
  _docker_find_image_entrypoint "$IMAGE" ENTRYPOINT
  ENTRYPOINT=$(echo "$ENTRYPOINT" | jq -r 'if type=="string" then . else join(" ") end')
  dc run $_RUN_OPTS --rm --no-deps $_RUN_REVERSE_PROXY_ENABLE_ARGS --entrypoint "$ENTRYPOINT" "$@"
else
  dc run $_RUN_OPTS --rm --no-deps $_RUN_REVERSE_PROXY_ENABLE_ARGS "$@"
fi
